services:
  nginx:
    build: ./requirements/nginx
    env_file: .env
    tty: true
    ports:
      - "443:443"
    networks:
      - front
  wordpress:
    build: ./requirements/wordpress
    env_file: .env
    tty: true
    ports:
      - "9000:9000"
    networks:
      - front
      - back
  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - "dbfiles:/var/lib/mysql"
    networks:
      - back
networks:
  front: {}
  back: {}
volumes:
  dbfiles:
    driver: local
    driver_opts:
      device: /home/cclaude
      o: bind
      type: none